In [1]:
import numpy as np
from IPython.display import display

from compcalc import *

# Exemplo 6.1 do Barbeiro

In [2]:
# Exemplo 6.1 do Barbeiro
mt = 28
t = 0.635 # mm
theta = 55
L = [
    [mt,+theta,t],
    [mt,-theta,t],
]

laminate = Laminate(L)
# np.set_printoptions(precision=3)

print('Exemplo 6.1 do Barbeiro:')

print('\n')
print('INPLANE STIFFNESS:')

print("\nPly 0 QT:")
display(laminate.laminate_stack[0].QT)

print("\nA:")
display(laminate.A)

print("\nB:")
display(laminate.B)

print("\nD:")
display(laminate.D)

print('\n')
print('OUT OF PLANE STIFFNESS:')

print("\nPly 0 QI:")
display(laminate.laminate_stack[0].QI)

print("\nPly 0 QIT:")
display(laminate.laminate_stack[0].QIT)


print("\nH:")
display(laminate.H)

# print("\nABD:\n")
# display(laminate.ABD)

# print("\nabd:\n")
# display(laminate.abd)

Exemplo 6.1 do Barbeiro:


INPLANE STIFFNESS:

Ply 0 QT:


array([[12.4016496 ,  5.70964889,  1.21713152],
       [ 5.70964889, 15.47166068,  3.00026153],
       [ 1.21713152,  3.00026153,  6.23855472]])


A:


array([[15.75009499,  7.25125409,  0.        ],
       [ 7.25125409, 19.64900906,  0.        ],
       [ 0.        ,  0.        ,  7.92296449]])


B:


array([[0.        , 0.        , 0.49077786],
       [0.        , 0.        , 1.20978046],
       [0.49077786, 1.20978046, 0.        ]])


D:


array([[2.11694402, 0.97462898, 0.        ],
       [0.97462898, 2.64099056, 0.        ],
       [0.        , 0.        , 1.06491245]])



OUT OF PLANE STIFFNESS:

Ply 0 QI:


array([[4.11155235, 0.        ],
       [0.        , 3.789     ]])


Ply 0 QIT:


array([[ 3.89511647, -0.15155003],
       [-0.15155003,  4.00543587]])


H:


array([[2.0611658 , 0.        ],
       [0.        , 2.11954315]])

In [3]:
# Exemplo 6.2 do Barbeiro
mt = 28
t = 0.635 # mm
theta = 0
L = [
    [mt,+theta,t]
]

print("\nLaminate list:")
laminate = Laminate(L)

print(laminate.laminate_list)

print("\nXXXX:")
# display(laminate.laminate_stack[0].thickness)

print(len(laminate.laminate_stack))


print('='*50)

print("\nPly 0 QT:")
print(laminate.laminate_stack[0].QT)

print("\nD:")
print(laminate.D)

print("\nd:")
display(np.linalg.inv(laminate.D))

# print("\nABD:")
# print(laminate.ABD)

# print("\nabd:")
abd = np.linalg.inv(laminate.ABD)
# print(abd)





print('\n'*3)

load_vector = np.array([0,0,0,1,0,0]) # [N_x, N_y, N_xy, M_x, M_y, M_xy] 
laminate.aply_load(load_vector.T)
laminate.print_deformation_vector()

print('~'*50)

print(np.dot(abd,load_vector))


Laminate list:
[[28, 0, 0.635, -0.0]]

XXXX:
1

Ply 0 QT:
[[20.8742658   3.26009417  0.        ]
 [ 3.26009417 11.89815391  0.        ]
 [ 0.          0.          3.789     ]]

D:
[[0.44540095 0.06956168 0.        ]
 [0.06956168 0.25387475 0.        ]
 [0.         0.         0.08084712]]

d:


array([[ 2.34554004, -0.64267797,  0.        ],
       [-0.64267797,  4.11504394,  0.        ],
       [ 0.        ,  0.        , 12.36902493]])





Deformation vector:
      u_x: 0.0
      u_y: 0.0
 gamma_xy: 0.0
      k_x: 2.345540036272178
      k_y: -0.6426779699385768
     k_xy: 0.0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 0.          0.          0.          2.34554004 -0.64267797  0.        ]


In [4]:
Zk = 0
Q = laminate.laminate_stack[0].Q

D0 = Q*(t*Zk**2 + (t**3)/12)

display(D0)


laminate.laminate_stack[0].print_lamina_deformation()

array([[0.44540095, 0.06956168, 0.        ],
       [0.06956168, 0.25387475, 0.        ],
       [0.        , 0.        , 0.08084712]])

Deformation:
[-0.74470896  0.20405026  0.        ]
Estresse:
[-0.040069    0.02812865  0.        ]


---
# Calculos de deformação do vaso de pressão

In [5]:
R_c = 60 # mm
r_pf = 21 # mm
b_ef = 42 # mm
b_er = 42 # mm
l_c = 88 # mm

alpha_c = np.asin(r_pf/R_c)

print("Alpha:")
print(alpha_c, "deg")
print(np.rad2deg(alpha_c), "deg")

alpha_c_deg = np.rad2deg(alpha_c)

# Criando o laminado
mt = 29
t_angleply = 0.125 #(1/4) # mm #* 10**-3 # m
t_hoop = t_angleply # 0.125 # mm

L = [
    [mt,+alpha_c_deg,t_angleply],
    [mt,-alpha_c_deg,t_angleply],
    [mt,+alpha_c_deg,t_angleply],
    [mt,-alpha_c_deg,t_angleply],
    [mt,+alpha_c_deg,t_angleply],
    [mt,-alpha_c_deg,t_angleply],
    [mt,90,t_hoop],
]

laminate = Laminate(L)

pressure = 4e-3 # GPa # 4e6 # Pa

# N_x = (pressure * np.pi * R_c**2)/(2 * np.pi * R_c) # N/m
N_x = (pressure * R_c)/(2) # [10e3 Nm] tensão longitudinal
N_y = pressure * R_c # [10e3 Nm]

load_vector = np.array([N_x,N_x,0,0,0,0]) # [N_x, N_y, N_xy, M_x, M_y, M_xy]

laminate.aply_load(load_vector)

print()
laminate.print_deformation_vector()

# print('\nSurface deformations:')
# laminate.laminate_stack[-1].print_lamina_deformation()



Alpha:
0.35757110364551026 deg
20.487315114722662 deg

Deformation vector:
      u_x: 0.0007753351743533289
      u_y: 0.004398335295963933
 gamma_xy: -3.0847150750516914e-19
      k_x: -0.002730545626650036
      k_y: 0.0100874188769729
     k_xy: -0.0033391410774119452


In [6]:

exp_ex = 0.00103
exp_ey = 0.00567

for t in [0.105,0.12,0.125,0.15,0.18]:
    print('='*50)
    print('Espessura =', t)
    print()

    for mt in [29,30,31,32]:
        L = [
        [mt,+alpha_c_deg,t],
        [mt,-alpha_c_deg,t],
        [mt,+alpha_c_deg,t],
        [mt,-alpha_c_deg,t],
        [mt,+alpha_c_deg,t],
        [mt,-alpha_c_deg,t],
        [mt,90,t],
        ]

        laminate = Laminate(L)

        pressure = 4e-3 # GPa # 4e6 # Pa

        # N_x = (pressure * np.pi * R_c**2)/(2 * np.pi * R_c) # N/m
        N_x = (pressure * R_c)/(2) # [10e3 Nm] tensão longitudinal
        N_y = pressure * R_c # [10e3 Nm]

        load_vector = np.array([N_x,N_x,0,0,0,0]) # [N_x, N_y, N_xy, M_x, M_y, M_xy]

        laminate.aply_load(load_vector)

        # print('Material = ', mt)

        ex = laminate.deformation_vector[0]
        ey = laminate.deformation_vector[1]
        

        print('E1 =',laminate.laminate_stack[0].properties['E1'])
        print('deformações ex,ey:')
        print(ex,ey)

        print('Erros em relação a média de ex,ey [%]:')
        print(
            100*((exp_ex-ex)/exp_ex),
            ';',
            100*((exp_ey-ey)/exp_ey)
            )
        print()

Espessura = 0.105

E1 = 146.94
deformações ex,ey:
0.0009230180647063441 0.0052361134475761096
Erros em relação a média de ex,ey [%]:
10.386595659578255 ; 7.652320148569491

E1 = 130.0
deformações ex,ey:
0.0010608203755466505 0.005755849272063529
Erros em relação a média de ex,ey [%]:
-2.9922694705485817 ; -1.5140965090569578

E1 = 120.0
deformações ex,ey:
0.0011620263445627993 0.006114183360649439
Erros em relação a média de ex,ey [%]:
-12.81809170512614 ; -7.833921704575644

E1 = 110.0
deformações ex,ey:
0.0012831656186197433 0.006520182018415283
Erros em relação a média de ex,ey [%]:
-24.579186273761472 ; -14.994391859176082

Espessura = 0.12

E1 = 146.94
deformações ex,ey:
0.0008076408066180508 0.004581599266629098
Erros em relação a média de ex,ey [%]:
21.588271202131 ; 19.195780129998273

E1 = 130.0
deformações ex,ey:
0.0009282178286033192 0.005036368113055588
Erros em relação a média de ex,ey [%]:
9.881764213269992 ; 11.175165554575168

E1 = 120.0
deformações ex,ey:
0.00101677305

In [7]:

exp_ex = 0.00103
exp_ey = 0.00567

t_angleply = 0.333/2
t_hoop = 0.25

for mt in [29,30,31,32]:


    L = [
    [mt,+alpha_c_deg,t_angleply],
    [mt,-alpha_c_deg,t_angleply],
    [mt,+alpha_c_deg,t_angleply],
    [mt,-alpha_c_deg,t_angleply],
    [mt,+alpha_c_deg,t_angleply],
    [mt,-alpha_c_deg,t_angleply],
    [mt,90,t_hoop],
    ]

    laminate = Laminate(L)

    print('E1 =',laminate.laminate_stack[0].properties['E1'])

    pressure = 4e-3 # GPa # 4e6 # Pa

    # N_x = (pressure * np.pi * R_c**2)/(2 * np.pi * R_c) # N/m
    N_x = (pressure * R_c)/(2) # [10e3 Nm] tensão longitudinal
    N_y = pressure * R_c # [10e3 Nm]

    load_vector = np.array([N_x,N_x,0,0,0,0]) # [N_x, N_y, N_xy, M_x, M_y, M_xy]

    laminate.aply_load(load_vector)

    # print('Material = ', mt)

    ex = laminate.deformation_vector[0]
    ey = laminate.deformation_vector[1]

    print('deformações ex,ey:')
    print(ex,ey)

    print('Erros em relação a média de ex,ey [%]:')
    print(
        100*((exp_ex-ex)/exp_ex),
        ';',
        100*((exp_ey-ey)/exp_ey)
        )
    print()

E1 = 146.94
deformações ex,ey:
0.0007015378997418826 0.00237321158924572
Erros em relação a média de ex,ey [%]:
31.889524296904607 ; 58.1444164154194

E1 = 130.0
deformações ex,ey:
0.0007960151672448282 0.002629260362517543
Erros em relação a média de ex,ey [%]:
22.71697405390018 ; 53.62856503496397

E1 = 120.0
deformações ex,ey:
0.0008645393933969291 0.002808124797686552
Erros em relação a média de ex,ey [%]:
16.06413656340495 ; 50.47398945879097

E1 = 110.0
deformações ex,ey:
0.0009457257831935795 0.003013118038853349
Erros em relação a média de ex,ey [%]:
8.181962796739867 ; 46.858588380011476

